### ISSUE TITLE
Two commitlint-bots ;)

### ISSUE THREAD

**Issue by paulirish** [z0al/commitlint-bot#3]
_Mostly opening a conversation here, I'm in no rush to do anything. And please don't feel pressure to support my usecases. :)_

-----

Soo I have my own bot with this name: https://github.com/paulirish/commitlintbot

However mine only cares about Pull Request titles and doesn't care about actual commit messages. So technically it probably makes more sense to be called `commitlint-pr-bot`. 

I created it as there was no other option at the time, but I'm happy to retire and and point to your project if a few things happen:

* Support linting a PR title
* Support ignoring commit messages
* Support`commitlint.config.js` (#1)
* Support [commitlint-config-cz](https://github.com/whizark/commitlint-config-cz) for a project to specify custom types/scopes

Again, we can also agree to keep our projects separate. That's totally fine with me. :) I just wanted to list these out in case you want to create the ultimate feature-rich commitlint bot. 🎉

**Comment by paulirish** [comment]
also, just left a link to your project from my readme :)
![image](https://user-images.githubusercontent.com/39191/32409110-b3a2a948-c162-11e7-9f0f-06b264663e8f.png)

**Comment by ahmed-taj** [comment]
> Support linting a PR title

I can happily support this scenario ;)

> Support ignoring commit messages

I think this needs a config file, something like this:
```yml
# File: .github/commitlint.yml
lint:
  title: true
  messages: false
```

> Support commitlint.config.js (#1)
> Support commitlint-config-cz for a project to specify custom types/scopes

I'm still not sure how can I support `.js` files ( #1 )

**Comment by pintergreg** [comment]
I think yaml is much more readable for a config file, please use that instead of any `.js` files.
Otherwise keep up the good work! Both of you!
