### ISSUE TITLE
Bot messages are still cumbersome und not useful for users

### ISSUE THREAD

**Issue by wzrdtales** [z0al/commitlint-bot#7]
Since I repeatedly receive questions, I will open this ticket here now. The bot message should include a link to the conventions, otherwise new users have no clue at all, what is happening.

So a link pointing the user to the convention, probably https://github.com/conventional-changelog/conventional-changelog/tree/35e60b5be6027fb2784c5103eee111f6f99b045e/packages/conventional-changelog-angular, would be immmensly helpful.

https://github.com/db-migrate/node-db-migrate/pull/549#issuecomment-368667802

**Comment by marionebl** [comment]
I think this is an issue with commitlint itself: https://github.com/marionebl/commitlint/issues/206 

Especially commits the conventional-commits-parser can’t derive a header (type, subject) from produce confusing error messages right now.

**Comment by caarlos0** [comment]
Agree as well... messages look really weird and are not very useful to someone who does not know the commit msg rules...

**Comment by abma** [comment]
yeah, what does "message may not be empty" and "type may not be empty" mean? wtf?

**Comment by caarlos0** [comment]
tried something at #18, please let me know what you think :)
